# Tommy Li (tommy.li@firefire.co), 2017-06-17

language: java

node_js:
  - "6"
  
jdk:
  - oraclejdk8

# dist: trusty
# sudo: required

services:
  - postgresql

addons:
  postgresql: "9.4"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/fenergy-ui/node_modules

before_script:
  - psql -f fenergy-db/src/main/resources/db/setup_db.sql -U postgres

#before_install:
#  - npm i -g npm@5.3.0
  
script:
  - ./gradlew fenergy-db:setupTestData build
