-- Tommy Li (tommy.li@firefire.co), 2017-02-09

CREATE DATABASE n12m;

CREATE USER 'n12m' IDENTIFIED BY 'n12m_password';
CREATE USER 'n12mread' IDENTIFIED BY 'n12mread_password';

GRANT SELECT, INSERT, DELETE, UPDATE, INDEX, CREATE, DROP, CREATE TEMPORARY TABLES, EXECUTE ON n12m.* TO 'n12m';
GRANT SELECT ON n12m.* TO 'n12mread';
