-- Tommy Li (tommy.li@firefire.co), 2017-02-09

CREATE DATABASE n12mci;

CREATE USER 'n12mci' IDENTIFIED BY 'n12mci_password';
CREATE USER 'n12mciread' IDENTIFIED BY 'n12mciread_password';

GRANT SELECT, INSERT, DELETE, UPDATE, INDEX, CREATE, DROP, ALTER, CREATE TEMPORARY TABLES, EXECUTE ON n12mci.* TO 'n12mci';
GRANT SELECT ON n12mci.* TO 'n12mciread';
