-- Tommy Li (tommy.li@firefire.co), 2017-05-13

-- Initial user setup script, run as postgres user
DROP SCHEMA IF EXISTS n12m CASCADE;
REVOKE ALL PRIVILEGES ON DATABASE prod FROM n12m;
REVOKE ALL PRIVILEGES ON DATABASE prod FROM n12mread;
REVOKE ALL PRIVILEGES ON DATABASE ci FROM n12mci;
REVOKE ALL PRIVILEGES ON DATABASE ci FROM n12mciread;

DROP USER IF EXISTS n12m;
DROP USER IF EXISTS n12mread;
DROP USER IF EXISTS n12mci;
DROP USER IF EXISTS n12mciread;

CREATE USER n12m WITH ENCRYPTED PASSWORD 'n12m_password';
CREATE USER n12mread WITH ENCRYPTED PASSWORD 'n12mread_password';
CREATE USER n12mci WITH ENCRYPTED PASSWORD 'n12mci_password';
CREATE USER n12mciread WITH ENCRYPTED PASSWORD 'n12mciread_password';

REVOKE ALL PRIVILEGES ON DATABASE prod FROM PUBLIC;
REVOKE ALL PRIVILEGES ON DATABASE prod FROM n12mci;
REVOKE ALL PRIVILEGES ON DATABASE prod FROM n12mciread;
REVOKE ALL PRIVILEGES ON DATABASE ci FROM PUBLIC;
REVOKE ALL PRIVILEGES ON DATABASE ci FROM n12m;
REVOKE ALL PRIVILEGES ON DATABASE ci FROM n12mread;
GRANT CONNECT, CREATE, TEMPORARY ON DATABASE prod TO n12m;
GRANT CONNECT ON DATABASE prod TO n12mread;
GRANT CONNECT, CREATE, TEMPORARY ON DATABASE ci TO n12mci;
GRANT CONNECT ON DATABASE ci TO n12mciread;

COMMIT;
