server:
  port: 8081

spring:
  jmx.enabled: false
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver: class-name=${n12m.db.driver}
    url: ${n12m.db.url}
    username: ${n12m.db.userid}
    password: ${n12m.db.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate.ddl-auto: none
    generate-ddl: false

logging:
  file: nm12.api.log
  path: /tmp/log/n12m

n12m:
  db:
    driver: org.postgresql.Driver
    schema: n12m
    url: jdbc:postgresql://localhost/test
    userid: n12mtest
    password: password

flyway:
  driver: ${n12m.db.driver}
  schemas: ${n12m.db.schema}
  url: ${n12m.db.url}
  user: ${n12m.db.userid}
  password: ${n12m.db.password}
  placeholder: true
  placeholders.schemaName: ${n12m.db.schema}
  placeholders.dbUserId: ${n12m.db.userid}

security:
  oauth2:
    client:
      client-id: fenergy
      client-secret: fenergysecret
      access-token-uri: http://localhost:8080/auth/oauth/token
      user-authorization-uri: http://localhost:8080/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/auth/me
