server:
  context-path: /
  port: 8080

spring:
  jmx.enabled: false

logging:
  file: fenergy.api.log
  path: /tmp/log/fenergy
  level:
    org.springframework.security: DEBUG

fenergy:
  oauth:
    client-id: fenergy-client-id
    client-secret: fenergy-client-secret
    
google:
  client:
    clientId: ${fenergy.oauth.google.client.id}
    clientSecret: ${fenergy.oauth.google.client.secret}
    scope: ["https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/userinfo.profile"]
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

github:
  client:
    clientId: ${fenergy.oauth.github.client.id}
    clientSecret: ${fenergy.oauth.github.client.secret}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
  resource:
    userInfoUri: https://api.github.com/user

security:
  oauth2:
    client:
      client-id: ${fenergy.oauth.client-id}
      client-secret: ${fenergy.oauth.client-secret}
      scope: read,write
      auto-approve-scopes: '.*'
      grant-types: authorization_code
  basic:
    enabled: false
  sessions: never

zuul:
#  ignored-services: '*'
  routes:
    n12m-api:
      path: /nem12/**
      url: http://localhost:8081/nem12
      stripPrefix: false


server:
  context-path: /nem12
  port: 8081

n12m:
  db:
    driver: org.postgresql.Driver
    schema: nem12
    url: jdbc:postgresql://localhost/test
    userid: n12mtest
    password: password
  oauth:
    auth-server-url: http://localhost:8080
    auth-server-client-id: fenergy-client-id
    auth-server-client-secret: fenergy-client-secret

spring:
  application:
    name: nem12-api
  jmx.enabled: false
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver: class-name=${n12m.db.driver}
    url: ${n12m.db.url}
    username: ${n12m.db.userid}
    password: ${n12m.db.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate.ddl-auto: none
    generate-ddl: false

logging:
  file: nm12.api.log
  path: /tmp/log/nem12
  level:
    org.springframework.security: DEBUG

flyway:
  driver: ${n12m.db.driver}
  schemas: ${n12m.db.schema}
  url: ${n12m.db.url}
  user: ${n12m.db.userid}
  password: ${n12m.db.password}
  placeholder: true
  placeholders.schemaName: ${n12m.db.schema}
  placeholders.dbUserId: ${n12m.db.userid}

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: ${n12m.oauth.auth-server-client-id}
      client-secret: ${n12m.oauth.auth-server-client-secret}
      access-token-uri: ${n12m.oauth.auth-server-url}/oauth/token
      user-authorization-uri: ${n12m.oauth.auth-server-url}/oauth/authorize
    resource:
      user-info-uri: ${n12m.oauth.auth-server-url}/me
  sessions: never
