server:
  port: 8080

spring:
  jmx.enabled: false

logging:
  file: fenergy.api.log
  path: /tmp/log/fenergy

google:
  client:
    clientId: ${fenergy.oauth.client.id}
    clientSecret: ${fenergy.oauth.client.secret}
    scope: ["https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/userinfo.profile"]
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    tokenName: authorization_code
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

security:
  basic:
    enabled: false
