server:
  port: 8080
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  error:
    include-exception: false
    include-stacktrace: never

logging:
  file: logs/fenergy.webapp.log
  level:
    co.firefire: INFO
    org.springframework.security: INFO

management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health.show-details: 'when_authorized'
  info.git.mode: full

fenergy:
  db:
    driver: org.postgresql.Driver
    schema: fenergy
    url: jdbc:postgresql://localhost/fenergytest
    userid: fenergytest
    password: fenergytest_password
  security:
    oauth2:
      resource:
        user-info-uri: https://authServerUrl/userinfo

spring:
  application:
    name: fenergy
  jmx.enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://authServerUrl
          jwk-set-uri: https://authServerUrl/.well-known/jwks.json

  datasource:
    driver: class-name=${fenergy.db.driver}
    url: ${fenergy.db.url}
    username: ${fenergy.db.userid}
    password: ${fenergy.db.password}
  flyway:
    schemas: ${fenergy.db.schema}
    url: ${fenergy.db.url}
    user: ${fenergy.db.userid}
    password: ${fenergy.db.password}
    placeholder-replacement: true
    placeholders:
      schemaName: ${fenergy.db.schema}
      dbUserId: ${fenergy.db.userid}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        cache:
          use_query_cache: true
          use_reference_entries: true
          use_second_level_cache: true
          use_structured_entries: true
        ddl-auto: none
        jdbc:
          batch_size: 500
          batch_versioned_data: true
          fetch_size: 200
          lob:
            non_contextual_creation: true
        order_inserts: true
        order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
  profiles:
    active: dev,authEnabled
  devtools:
    add-properties: false
